//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobile.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mobile.Language.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string BTN_COMM_020 {
            get {
                return ResourceManager.GetString("BTN_COMM_020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string BTN_COMM_021 {
            get {
                return ResourceManager.GetString("BTN_COMM_021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 Minutes.
        /// </summary>
        internal static string BTN_DELV_022 {
            get {
                return ResourceManager.GetString("BTN_DELV_022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 Minutes.
        /// </summary>
        internal static string BTN_DELV_023 {
            get {
                return ResourceManager.GetString("BTN_DELV_023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 45 Minutes.
        /// </summary>
        internal static string BTN_DELV_024 {
            get {
                return ResourceManager.GetString("BTN_DELV_024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Hour.
        /// </summary>
        internal static string BTN_DELV_025 {
            get {
                return ResourceManager.GetString("BTN_DELV_025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string BTN_DELV_026 {
            get {
                return ResourceManager.GetString("BTN_DELV_026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mom.
        /// </summary>
        internal static string BTN_HOME_001 {
            get {
                return ResourceManager.GetString("BTN_HOME_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baby.
        /// </summary>
        internal static string BTN_HOME_002 {
            get {
                return ResourceManager.GetString("BTN_HOME_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string BTN_LOGI_001 {
            get {
                return ResourceManager.GetString("BTN_LOGI_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mom.
        /// </summary>
        internal static string BTN_MAIN_001 {
            get {
                return ResourceManager.GetString("BTN_MAIN_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baby.
        /// </summary>
        internal static string BTN_MAIN_002 {
            get {
                return ResourceManager.GetString("BTN_MAIN_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mom List.
        /// </summary>
        internal static string BTN_MAIN_003 {
            get {
                return ResourceManager.GetString("BTN_MAIN_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Mom.
        /// </summary>
        internal static string BTN_MAIN_004 {
            get {
                return ResourceManager.GetString("BTN_MAIN_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Mom.
        /// </summary>
        internal static string BTN_MAIN_005 {
            get {
                return ResourceManager.GetString("BTN_MAIN_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appoinment Mom List.
        /// </summary>
        internal static string BTN_MAIN_006 {
            get {
                return ResourceManager.GetString("BTN_MAIN_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Mom Appoinment.
        /// </summary>
        internal static string BTN_MAIN_007 {
            get {
                return ResourceManager.GetString("BTN_MAIN_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baby List.
        /// </summary>
        internal static string BTN_MAIN_008 {
            get {
                return ResourceManager.GetString("BTN_MAIN_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Baby.
        /// </summary>
        internal static string BTN_MAIN_009 {
            get {
                return ResourceManager.GetString("BTN_MAIN_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Baby.
        /// </summary>
        internal static string BTN_MAIN_010 {
            get {
                return ResourceManager.GetString("BTN_MAIN_010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baby Appoinment List.
        /// </summary>
        internal static string BTN_MAIN_011 {
            get {
                return ResourceManager.GetString("BTN_MAIN_011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Baby Appoinment.
        /// </summary>
        internal static string BTN_MAIN_012 {
            get {
                return ResourceManager.GetString("BTN_MAIN_012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Babies.
        /// </summary>
        internal static string CAP_BABY {
            get {
                return ResourceManager.GetString("CAP_BABY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baby Appointments.
        /// </summary>
        internal static string CAP_BABY_APPOINTMENTS {
            get {
                return ResourceManager.GetString("CAP_BABY_APPOINTMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Baby Health.
        /// </summary>
        internal static string CAP_BABY_HEALTH {
            get {
                return ResourceManager.GetString("CAP_BABY_HEALTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string CAP_CONFIRM {
            get {
                return ResourceManager.GetString("CAP_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Appoinment.
        /// </summary>
        internal static string CAP_CREATE_APPOINMENT {
            get {
                return ResourceManager.GetString("CAP_CREATE_APPOINMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Baby.
        /// </summary>
        internal static string CAP_CREATE_BABY {
            get {
                return ResourceManager.GetString("CAP_CREATE_BABY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Mother.
        /// </summary>
        internal static string CAP_CREATE_MOTHER {
            get {
                return ResourceManager.GetString("CAP_CREATE_MOTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Master Data.
        /// </summary>
        internal static string CAP_DOWNLOAD_MASTERDATA {
            get {
                return ResourceManager.GetString("CAP_DOWNLOAD_MASTERDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string CAP_GENDER {
            get {
                return ResourceManager.GetString("CAP_GENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string CAP_GRD_DATE {
            get {
                return ResourceManager.GetString("CAP_GRD_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string CAP_LOADING {
            get {
                return ResourceManager.GetString("CAP_LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging Out.
        /// </summary>
        internal static string CAP_LOG_OUT {
            get {
                return ResourceManager.GetString("CAP_LOG_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mom Baby.
        /// </summary>
        internal static string CAP_LOGIN {
            get {
                return ResourceManager.GetString("CAP_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Baby.
        /// </summary>
        internal static string CAP_MODIFY_BABY {
            get {
                return ResourceManager.GetString("CAP_MODIFY_BABY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Mother.
        /// </summary>
        internal static string CAP_MODIFY_MOTHER {
            get {
                return ResourceManager.GetString("CAP_MODIFY_MOTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Mother Health.
        /// </summary>
        internal static string CAP_MOM_HEALTH {
            get {
                return ResourceManager.GetString("CAP_MOM_HEALTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mothers.
        /// </summary>
        internal static string CAP_MOTHER {
            get {
                return ResourceManager.GetString("CAP_MOTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother Appointments.
        /// </summary>
        internal static string CAP_MOTHER_APPOINTMENTS {
            get {
                return ResourceManager.GetString("CAP_MOTHER_APPOINTMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string CAP_SAVE {
            get {
                return ResourceManager.GetString("CAP_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        internal static string CAP_SAVING {
            get {
                return ResourceManager.GetString("CAP_SAVING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string CAP_SETTINGS {
            get {
                return ResourceManager.GetString("CAP_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string CAP_SETTINGS_ABOUT {
            get {
                return ResourceManager.GetString("CAP_SETTINGS_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        internal static string CAP_SIGNATURE {
            get {
                return ResourceManager.GetString("CAP_SIGNATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel Time.
        /// </summary>
        internal static string CAP_TRAVEL_TIME {
            get {
                return ResourceManager.GetString("CAP_TRAVEL_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occoured!.
        /// </summary>
        internal static string ERR_UN_EXPECTED {
            get {
                return ResourceManager.GetString("ERR_UN_EXPECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to server! Check the connection..
        /// </summary>
        internal static string ERR_UNABLE_TO_CONNECT {
            get {
                return ResourceManager.GetString("ERR_UNABLE_TO_CONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name:.
        /// </summary>
        internal static string LBL_DATA_001 {
            get {
                return ResourceManager.GetString("LBL_DATA_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name:.
        /// </summary>
        internal static string LBL_DATA_002 {
            get {
                return ResourceManager.GetString("LBL_DATA_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIC:.
        /// </summary>
        internal static string LBL_DATA_003 {
            get {
                return ResourceManager.GetString("LBL_DATA_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOB:.
        /// </summary>
        internal static string LBL_DATA_004 {
            get {
                return ResourceManager.GetString("LBL_DATA_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:.
        /// </summary>
        internal static string LBL_DATA_005 {
            get {
                return ResourceManager.GetString("LBL_DATA_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        internal static string LBL_DATA_006 {
            get {
                return ResourceManager.GetString("LBL_DATA_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupation:.
        /// </summary>
        internal static string LBL_DATA_007 {
            get {
                return ResourceManager.GetString("LBL_DATA_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string LBL_DATA_008 {
            get {
                return ResourceManager.GetString("LBL_DATA_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Appointment DateTime:.
        /// </summary>
        internal static string LBL_DATA_009 {
            get {
                return ResourceManager.GetString("LBL_DATA_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string LBL_DATA_010 {
            get {
                return ResourceManager.GetString("LBL_DATA_010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Condition:.
        /// </summary>
        internal static string LBL_DATA_011 {
            get {
                return ResourceManager.GetString("LBL_DATA_011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight (kg):.
        /// </summary>
        internal static string LBL_DATA_012 {
            get {
                return ResourceManager.GetString("LBL_DATA_012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Pressure (mmHg):.
        /// </summary>
        internal static string LBL_DATA_013 {
            get {
                return ResourceManager.GetString("LBL_DATA_013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glucouse Level (mmol/L ):.
        /// </summary>
        internal static string LBL_DATA_014 {
            get {
                return ResourceManager.GetString("LBL_DATA_014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaccine:.
        /// </summary>
        internal static string LBL_DATA_015 {
            get {
                return ResourceManager.GetString("LBL_DATA_015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction:.
        /// </summary>
        internal static string LBL_DATA_016 {
            get {
                return ResourceManager.GetString("LBL_DATA_016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender:.
        /// </summary>
        internal static string LBL_DATA_017 {
            get {
                return ResourceManager.GetString("LBL_DATA_017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height (cm):.
        /// </summary>
        internal static string LBL_DATA_018 {
            get {
                return ResourceManager.GetString("LBL_DATA_018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother:.
        /// </summary>
        internal static string LBL_DATA_019 {
            get {
                return ResourceManager.GetString("LBL_DATA_019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed By:.
        /// </summary>
        internal static string LBL_DELV_017 {
            get {
                return ResourceManager.GetString("LBL_DELV_017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please rate your satisfaction level:.
        /// </summary>
        internal static string LBL_DELV_035 {
            get {
                return ResourceManager.GetString("LBL_DELV_035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for rating!.
        /// </summary>
        internal static string LBL_DELV_036 {
            get {
                return ResourceManager.GetString("LBL_DELV_036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Sign above the line.
        /// </summary>
        internal static string LBL_DELV_052 {
            get {
                return ResourceManager.GetString("LBL_DELV_052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string LBL_DELV_053 {
            get {
                return ResourceManager.GetString("LBL_DELV_053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List View.
        /// </summary>
        internal static string LBL_LIST_VIEW {
            get {
                return ResourceManager.GetString("LBL_LIST_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        internal static string LBL_LOGI_001 {
            get {
                return ResourceManager.GetString("LBL_LOGI_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LBL_LOGI_002 {
            get {
                return ResourceManager.GetString("LBL_LOGI_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © Copyright to Cardiff.
        /// </summary>
        internal static string LBL_LOGI_003 {
            get {
                return ResourceManager.GetString("LBL_LOGI_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        internal static string LBL_LOGI_004 {
            get {
                return ResourceManager.GetString("LBL_LOGI_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        internal static string LBL_LOGI_0041 {
            get {
                return ResourceManager.GetString("LBL_LOGI_0041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string LBL_LOGI_005 {
            get {
                return ResourceManager.GetString("LBL_LOGI_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string LBL_LOGI_006 {
            get {
                return ResourceManager.GetString("LBL_LOGI_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string LBL_LOGI_007 {
            get {
                return ResourceManager.GetString("LBL_LOGI_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Data.
        /// </summary>
        internal static string LBL_LOGI_009 {
            get {
                return ResourceManager.GetString("LBL_LOGI_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map View.
        /// </summary>
        internal static string LBL_MAP_VIEW {
            get {
                return ResourceManager.GetString("LBL_MAP_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string LBL_PREP_001 {
            get {
                return ResourceManager.GetString("LBL_PREP_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother Name:.
        /// </summary>
        internal static string LBL_PREP_008 {
            get {
                return ResourceManager.GetString("LBL_PREP_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIC:.
        /// </summary>
        internal static string LBL_PREP_999 {
            get {
                return ResourceManager.GetString("LBL_PREP_999", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This functionality is available only in online mode..
        /// </summary>
        internal static string MSG_COM_001 {
            get {
                return ResourceManager.GetString("MSG_COM_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to create a new mother?.
        /// </summary>
        internal static string MSG_COM_002 {
            get {
                return ResourceManager.GetString("MSG_COM_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to create a new baby?.
        /// </summary>
        internal static string MSG_COM_003 {
            get {
                return ResourceManager.GetString("MSG_COM_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to create an appointment?.
        /// </summary>
        internal static string MSG_COM_004 {
            get {
                return ResourceManager.GetString("MSG_COM_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId and Password not specified!.
        /// </summary>
        internal static string MSG_COM_011 {
            get {
                return ResourceManager.GetString("MSG_COM_011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId not specified!.
        /// </summary>
        internal static string MSG_COM_012 {
            get {
                return ResourceManager.GetString("MSG_COM_012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password not specified!.
        /// </summary>
        internal static string MSG_COM_013 {
            get {
                return ResourceManager.GetString("MSG_COM_013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong username and / or password!.
        /// </summary>
        internal static string MSG_COM_014 {
            get {
                return ResourceManager.GetString("MSG_COM_014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User group doesn&apos;t have any functions assigned!.
        /// </summary>
        internal static string MSG_COM_019 {
            get {
                return ResourceManager.GetString("MSG_COM_019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to log out? !&amp;#x0a; If not, press CANCEL to return to the Main Menu..
        /// </summary>
        internal static string MSG_COM_021 {
            get {
                return ResourceManager.GetString("MSG_COM_021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing Data....
        /// </summary>
        internal static string MSG_COM_027 {
            get {
                return ResourceManager.GetString("MSG_COM_027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature and Signer name are mandatory..
        /// </summary>
        internal static string MSG_DEL_041 {
            get {
                return ResourceManager.GetString("MSG_DEL_041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inform travel time? ({0} : {1}).
        /// </summary>
        internal static string MSG_DEL_156 {
            get {
                return ResourceManager.GetString("MSG_DEL_156", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending start notification....
        /// </summary>
        internal static string MSG_DEL_158 {
            get {
                return ResourceManager.GetString("MSG_DEL_158", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending arriving notification....
        /// </summary>
        internal static string MSG_DEL_159 {
            get {
                return ResourceManager.GetString("MSG_DEL_159", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending completed notification....
        /// </summary>
        internal static string MSG_DEL_160 {
            get {
                return ResourceManager.GetString("MSG_DEL_160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input estimated time of arrival ?.
        /// </summary>
        internal static string MSG_DEL_162 {
            get {
                return ResourceManager.GetString("MSG_DEL_162", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading Baby Data.
        /// </summary>
        internal static string MSG_INI_001 {
            get {
                return ResourceManager.GetString("MSG_INI_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading Mother Data.
        /// </summary>
        internal static string MSG_INI_002 {
            get {
                return ResourceManager.GetString("MSG_INI_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading Baby Health Data.
        /// </summary>
        internal static string MSG_INI_003 {
            get {
                return ResourceManager.GetString("MSG_INI_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading Mother Health Data.
        /// </summary>
        internal static string MSG_INI_004 {
            get {
                return ResourceManager.GetString("MSG_INI_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Failed.
        /// </summary>
        internal static string MSG_INI_005 {
            get {
                return ResourceManager.GetString("MSG_INI_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Former date is not allowed.
        /// </summary>
        internal static string MSG_INI_069 {
            get {
                return ResourceManager.GetString("MSG_INI_069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future date is not allowed.
        /// </summary>
        internal static string MSG_INI_070 {
            get {
                return ResourceManager.GetString("MSG_INI_070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        internal static string MSG_INI_071 {
            get {
                return ResourceManager.GetString("MSG_INI_071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Saved Successfully !.
        /// </summary>
        internal static string MSG_SAVE {
            get {
                return ResourceManager.GetString("MSG_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Saved Locally Successfully !.
        /// </summary>
        internal static string MSG_SAVE_LOCALLY {
            get {
                return ResourceManager.GetString("MSG_SAVE_LOCALLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Number.
        /// </summary>
        internal static string MSG_SET_028 {
            get {
                return ResourceManager.GetString("MSG_SET_028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used in Application.
        /// </summary>
        internal static string MSG_SET_029 {
            get {
                return ResourceManager.GetString("MSG_SET_029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string MSG_SET_030 {
            get {
                return ResourceManager.GetString("MSG_SET_030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may change the language of the application.
        /// </summary>
        internal static string MSG_SET_031 {
            get {
                return ResourceManager.GetString("MSG_SET_031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        internal static string MSG_SET_032 {
            get {
                return ResourceManager.GetString("MSG_SET_032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer.
        /// </summary>
        internal static string MSG_SET_033 {
            get {
                return ResourceManager.GetString("MSG_SET_033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string MSG_SET_038 {
            get {
                return ResourceManager.GetString("MSG_SET_038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application version, Device info.
        /// </summary>
        internal static string MSG_SET_039 {
            get {
                return ResourceManager.GetString("MSG_SET_039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Model.
        /// </summary>
        internal static string MSG_SET_041 {
            get {
                return ResourceManager.GetString("MSG_SET_041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating System.
        /// </summary>
        internal static string MSG_SET_042 {
            get {
                return ResourceManager.GetString("MSG_SET_042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique ID.
        /// </summary>
        internal static string MSG_SET_043 {
            get {
                return ResourceManager.GetString("MSG_SET_043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Database.
        /// </summary>
        internal static string MSG_SET_045 {
            get {
                return ResourceManager.GetString("MSG_SET_045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Local Database.
        /// </summary>
        internal static string MSG_SET_046 {
            get {
                return ResourceManager.GetString("MSG_SET_046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to send the delivery notification!.
        /// </summary>
        internal static string SVR_DEL_018 {
            get {
                return ResourceManager.GetString("SVR_DEL_018", resourceCulture);
            }
        }
    }
}
